version: '3.7'

services:
    caddy:
        image: caddy:2.0.0-alpine
        ports:
          - 5000:80
        volumes:
          - /Users/tcs/WebStormProjects/rnb-electronics/Caddyfile:/etc/Caddyfile
          - /Users/tcs/WebStormProjects/rnb-electronics:/usr/share/caddy
          - /Users/tcs/WebStormProjects/rnb-depots/data:/data
        deploy:
          replicas: 2
          update_config:
            parallelism: 1
            delay: 10s
          restart_policy:
            condition: on-failure
        networks:
            - frontend
    db:
        image: mariadb:10.4.12
        ports:
          - 33060:3306
        environment:
          - MYSQL_ROOT_PASSWORD=secret
        volumes:
          - /Users/tcs/WebStormProjects/rnb-depots/db:/var/lib/mysql
        networks:
          - backend
        deploy:

    places:
        image: tsawler/rnb-data:1.0.1
        ports:
          - 8080:8080
        depends_on:
          - db
        environment:
          WAIT_HOSTS_TIMEOUT: 60
          WAIT_HOSTS: db:3306
          DB_HOST: db
        deploy:
          replicas: 2
          update_config:
            parallelism: 1
            delay: 10s
          restart_policy:
            condition: on-failure
        networks:
          - backend
          - frontend

networks:
    frontend:
    backend:


